[package]
name = "rustls-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustls = { package = "rustls-jls", path = "../rustls", default-features = false, features = ["std", "tls12"] }
