[package]
name = "rustls-fuzzing-provider"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rustls = { package = "rustls-jls", path = "../rustls-jls", default-features = false, features = ["logging", "std", "tls12"] }

[dev-dependencies]
env_logger = { workspace = true }
